Add Publish_Subdirectory_To_Branch() command.
Publishes a given subdirectory to a specific branch in the currently checked
out git repository. i.e. the contents of <subdirectory> become the root
contents of <branch>. If [remote] is not specified, the current remote is
used (typically origin).
<subdirectory> is assumed to be related to the current working directory.

Usage: Publish_Subdirectory <branch> <subdirectory> <commit msg> [remote]

diff --git a/lib-ci b/lib-ci
--- a/lib-ci
+++ b/lib-ci
@@ -181,4 +181,66 @@ Array_Contains () {
     echo $in
 }
 
+# Publishes a given subdirectory to a specific branch in the currently checked
+# out git repository. i.e. the contents of <subdirectory> become the root
+# contents of <branch>. If [remote] is not specified, the current remote is
+# used (typically origin).
+# <subdirectory> is assumed to be related to the current working directory.
+# Usage: Publish_Subdirectory <branch> <subdirectory> <commit msg> [remote]
+Publish_Subdirectory_To_Branch() {
+    local git_branch="$1"
+    local subdirectory="$2"
+    local commit_msg="$3"
+    local remote="$4"
+
+    if [ -z "$remote" ]; then
+        # Figure out a default remote, or fail.
+        remote=$(git remote -v | cut -f2 | cut -d' ' -f1 | head -n1)
+        if [ -z $remote ]; then
+            echoerr "No git remote could be identified and none specified. Aborting."
+            exit 1
+        fi
+    fi
+    
+    if [ -z "$git_branch" ]; then
+        echoerr "No git branch specified. Aborting."
+        exit 1
+    fi
+    
+    # Don't mess up .git dir branch state in real work dir - store where we were
+    # Only relevant for local testers.
+    ORIG_BRANCH=$(git symbolic-ref HEAD)
+    
+    ORIG_GIT_DIR=$GIT_DIR
+    ORIG_GIT_WORK_TREE=$GIT_WORK_TREE
+    
+    export GIT_DIR=$(pwd)/.git
+    export GIT_WORK_TREE=$(pwd)/$subdirectory
+    
+    git symbolic-ref HEAD refs/heads/$git_branch
+    
+    if ! git show-ref refs/remotes/$remote/$git_branch; then
+        # Create an empty branch.
+        echoerr "Warning: $git_branch will be created (it did not exist on the remote)"
+        touch $GIT_WORK_TREE/.gitkeep
+        git add $GIT_WORK_TREE/.gitkeep
+        git commit -m "Initial commit"
+    else
+        # Track the existent branch
+        echo "Checking out current $git_branch"
+        git branch $git_branch -f $remote/$git_branch
+        
+        # Read the tree into the index so the build result is auto-available
+        git read-tree $git_branch
+    fi
+    
+    git add -A
+    git commit -m "$commit_msg"
+    
+    git symbolic-ref HEAD $ORIG_BRANCH
+    
+    export GIT_DIR=$ORIG_GIT_DIR
+    export GIT_WORK_TREE=$ORIG_GIT_WORK_TREE
+}
+
 set +o nounset
